// Catalog lifted from _source/editor.html. `window.X` references became real
// imports, and the nine templates that shipped with `fields: []` now have
// field definitions — their components were given props with identical
// defaults, so nothing renders differently.
import { XHeader, LinkedInCover, TwitchBanner } from '@/components/avatars-covers';
import {
  PrivacyPost, FeaturePost, QuotePost, StatPost,
  LaunchPost, HotTakePost, MemePost, BlogPromoPost,
} from '@/components/posts';
import {
  StoryPrivacy, StoryStat, StoryLaunch, StoryQuote,
  ThumbnailTutorial, ThumbnailHotTake, ThumbnailLaunch,
} from '@/components/stories-thumbs';
import {
  WhyBuiltPost, ManifestoPost, ProblemSolutionPost, FAQPost, ComparisonPost,
  UseCasePost, ReceiptPost, CommunityPost, CTAPost,
  CarouselSlide1, CarouselSlide2, CarouselSlide5,
} from '@/components/engagement-posts';

const TEMPLATES = [
  // === Square posts ===
  { id: 'privacy', group: 'Square · 1080×1080', name: 'Privacy / TEE post', dot: '#5866C2', w: 1080, h: 1080,
    Component: PrivacyPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'How PrivexBot is different' },
      { k: 'title', label: 'Title (use newline)', type: 'textarea', def: 'Your prompts never\nleave the enclave.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Inference runs inside a Trusted Execution Environment. PrivexBot, the model host, and your hosting provider cannot read your prompts or your user\'s messages. Cryptographically verified.' },
      { k: 'stat', label: 'Badge', type: 'text', def: 'TEE-attested' },
    ],
  },
  { id: 'feature', group: 'Square · 1080×1080', name: 'Feature announcement', dot: '#3947A8', w: 1080, h: 1080,
    Component: FeaturePost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Now shipping' },
      { k: 'title', label: 'Title', type: 'textarea', def: 'Visual chatflow\nbuilder, v2.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Drag nodes. Branch on intent. Inspect runs. The new builder ships with 14 nodes including OpenAI, Anthropic, vector search, HTTP, and webhook.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Read the changelog' },
    ],
  },
  { id: 'quote', group: 'Square · 1080×1080', name: 'Customer quote', dot: '#0A0C10', w: 1080, h: 1080,
    Component: QuotePost,
    fields: [
      { k: 'quote', label: 'Quote', type: 'textarea', def: 'Our customers asked us to add AI search. They did not ask us to share their queries with five vendors. PrivexBot was the only platform that let us say yes to one without saying yes to the other.' },
      { k: 'author', label: 'Author', type: 'text', def: 'Maya Okafor' },
      { k: 'role', label: 'Role', type: 'text', def: 'CTO, North Loop Health' },
    ],
  },
  { id: 'stat', group: 'Square · 1080×1080', name: 'Big stat card', dot: '#3E8A5E', w: 1080, h: 1080,
    Component: StatPost,
    fields: [
      { k: 'number', label: 'Number', type: 'text', def: '14 min' },
      { k: 'caption', label: 'Caption', type: 'textarea', def: 'Median time-to-deploy for a new chatbot — from blank workspace to live on Discord.' },
      { k: 'context', label: 'Context', type: 'text', def: 'Across 1,247 bots created in April.' },
      { k: 'source', label: 'Source', type: 'text', def: 'PrivexBot platform metrics, April 2026' },
    ],
  },
  { id: 'launch', group: 'Square · 1080×1080', name: 'Launch / milestone', dot: '#7DC79A', w: 1080, h: 1080,
    Component: LaunchPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Launch week · Day 03' },
      { k: 'title', label: 'Title', type: 'textarea', def: 'WhatsApp deploys.\nNow generally available.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Connect your WhatsApp Business number to any PrivexBot agent. End-to-end encrypted messages stay encrypted — we never see your customer conversations.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Deploy your first bot' },
    ],
  },
  { id: 'hottake', group: 'Square · 1080×1080', name: 'Industry hot take', dot: '#3947A8', w: 1080, h: 1080,
    Component: HotTakePost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Industry pov' },
      { k: 'hook', label: 'Hook', type: 'text', def: 'If your AI vendor can read your prompts,' },
      { k: 'payoff', label: 'Payoff', type: 'text', def: 'they can sell them, leak them, or lose them.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'There are three companies between your customer and an answer. The fewer of them that ever see the data, the safer your business. That\'s why every PrivexBot inference runs inside a hardware enclave.' },
    ],
  },
  { id: 'meme', group: 'Square · 1080×1080', name: 'Lighthearted / meme', dot: '#D97706', w: 1080, h: 1080,
    Component: MemePost,
    fields: [
      { k: 'setup', label: 'Setup', type: 'text', def: 'Your AI vendor:' },
      { k: 'punchline', label: 'Punchline', type: 'text', def: '"We take privacy seriously."' },
      { k: 'reveal', label: 'Reveal', type: 'text', def: 'Also your AI vendor:' },
      { k: 'closer', label: 'Closer', type: 'text', def: '*reads your prompts to train their next model*' },
    ],
  },
  { id: 'blog', group: 'Square · 1080×1080', name: 'Blog promo', dot: '#5866C2', w: 1080, h: 1080,
    Component: BlogPromoPost,
    fields: [
      { k: 'category', label: 'Category', type: 'text', def: 'Engineering' },
      { k: 'readTime', label: 'Read time', type: 'text', def: '8 min' },
      { k: 'title', label: 'Title', type: 'textarea', def: 'Why we built our chatflow engine on a CRDT.' },
      { k: 'excerpt', label: 'Excerpt', type: 'textarea', def: 'Real-time collaboration sounds great until two engineers drag the same node. Here\'s how we built collaborative editing for visual workflows — and the three mistakes we made first.' },
      { k: 'author', label: 'Author', type: 'text', def: 'Sasha Chen · Staff Engineer' },
    ],
  },
  // === Engagement / mission posts ===
  { id: 'why', group: 'Engagement · 1080×1080', name: 'Why we built it (founder story)', dot: '#3947A8', w: 1080, h: 1080,
    Component: WhyBuiltPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Why we built PrivexBot' },
      { k: 'story', label: 'Setup', type: 'textarea', def: 'In 2024 we watched a hospital deploy an AI assistant — and quietly send every patient question to three vendors who could read them.' },
      { k: 'reframe', label: 'Reframe (highlighted)', type: 'textarea', def: 'The hospital wasn\'t reckless. They had no other choice.' },
      { k: 'resolution', label: 'Resolution', type: 'textarea', def: 'We built PrivexBot to give them one. Now every inference happens inside a hardware enclave. We can\'t read your prompts. Neither can your model host. Neither can anyone else.' },
      { k: 'signoff', label: 'Sign-off', type: 'text', def: '— The PrivexBot team' },
    ],
  },
  { id: 'manifesto', group: 'Engagement · 1080×1080', name: 'Manifesto · what we believe', dot: '#0A0C10', w: 1080, h: 1080,
    Component: ManifestoPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'What we believe' },
      { k: 'line1', label: 'Line 1', type: 'text', def: 'Privacy is not' },
      { k: 'line2', label: 'Line 2 (crossed-out)', type: 'text', def: 'a feature.' },
      { k: 'line3', label: 'Line 3 (highlight)', type: 'text', def: 'It\'s the foundation.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Every AI tool on the market asks you to trust three things you can\'t verify: the vendor, the model host, and the network in between. PrivexBot replaces trust with proof. Every inference is cryptographically attested.' },
    ],
  },
  { id: 'problem', group: 'Engagement · 1080×1080', name: 'Problem / solution split', dot: '#E5484D', w: 1080, h: 1080,
    Component: ProblemSolutionPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'The problem we solve' },
      { k: 'problem', label: 'Problem', type: 'textarea', def: 'Most "private" AI tools still upload your prompts to a third party.' },
      { k: 'problemDetail', label: 'Problem detail', type: 'textarea', def: 'You agreed to a privacy policy. The privacy policy says they "may use your data to improve our service."' },
      { k: 'solution', label: 'Solution', type: 'textarea', def: 'PrivexBot runs every inference inside a hardware enclave.' },
      { k: 'solutionDetail', label: 'Solution detail', type: 'textarea', def: 'Even our engineers can\'t see what you send. We have receipts to prove it.' },
    ],
  },
  { id: 'faq', group: 'Engagement · 1080×1080', name: 'Did you know · educational', dot: '#3E8A5E', w: 1080, h: 1080,
    Component: FAQPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Did you know?' },
      { k: 'question', label: 'Question', type: 'textarea', def: 'When you send a message to your favourite AI chatbot, how many companies get to read it?' },
      { k: 'answer', label: 'Answer (big number)', type: 'text', def: '3' },
      { k: 'answerLabel', label: 'Answer label', type: 'text', def: 'companies, on average' },
      { k: 'footer', label: 'Footer', type: 'text', def: 'With PrivexBot: zero.' },
    ],
  },
  { id: 'usecase', group: 'Engagement · 1080×1080', name: 'Use case · healthcare', dot: '#5866C2', w: 1080, h: 1080,
    Component: UseCasePost,
    fields: [
      { k: 'industry', label: 'Industry', type: 'text', def: 'Healthcare' },
      { k: 'headline', label: 'Headline', type: 'textarea', def: 'How a 200-bed hospital deployed AI patient triage without breaking HIPAA.' },
      { k: 'quote', label: 'Quote', type: 'textarea', def: '"PrivexBot was the only platform where our compliance team didn\'t require a six-month audit."' },
      { k: 'quoteBy', label: 'Quote by', type: 'text', def: '— Director of Clinical IT, North Loop Health' },
    ],
  },
  { id: 'receipt', group: 'Engagement · 1080×1080', name: 'Attestation receipt · proof', dot: '#3E8A5E', w: 1080, h: 1080,
    Component: ReceiptPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Proof, not promises' },
      { k: 'title', label: 'Title', type: 'textarea', def: 'Here\'s the cryptographic receipt for your last inference.' },
      { k: 'body', label: 'Body (use \\n for line breaks)', type: 'textarea', def: 'Every PrivexBot inference signs an attestation that proves:\n· which model ran\n· that it ran inside a verified enclave\n· that no one logged the prompt\n\nYou can verify it yourself. Or we can.' },
    ],
  },
  { id: 'cta', group: 'Engagement · 1080×1080', name: 'CTA · sign up', dot: '#3947A8', w: 1080, h: 1080,
    Component: CTAPost,
    fields: [
      { k: 'hook', label: 'Hook', type: 'textarea', def: 'Stop trusting AI vendors with your customer data.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Build your first private chatbot in 15 minutes. No credit card. No data leaving the enclave.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Start free at privexbot.com' },
      { k: 'proof', label: 'Proof', type: 'text', def: 'Trusted by teams in healthcare, fintech, and legal.' },
    ],
  },
  { id: 'community', group: 'Engagement · 1080×1080', name: 'Community spotlight', dot: '#0A0C10', w: 1080, h: 1080,
    Component: CommunityPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Community spotlight' },
      { k: 'shoutout', label: 'Headline', type: 'text', def: 'Built with PrivexBot:' },
      { k: 'callout', label: 'Callout', type: 'text', def: 'Add your bot to the registry → privexbot.com/community' },
      { k: 'examples', label: 'Projects', type: 'rows', cols: [
        { k: 'icon', label: 'Initial', w: 60 }, { k: 'name', label: 'Name' }, { k: 'tagline', label: 'Tagline' }],
        def: [
          { name: 'ClinicHub', tagline: 'Patient triage for community clinics', icon: 'C' },
          { name: 'Lexley', tagline: 'AI paralegal for solo lawyers', icon: 'L' },
          { name: 'Sift', tagline: 'Resume review without saving resumes', icon: 'S' },
          { name: 'Helmet', tagline: 'Security review bot for GitHub PRs', icon: 'H' },
          { name: 'Carto', tagline: 'Internal docs search for engineering teams', icon: 'C' },
          { name: 'Petra', tagline: 'Therapist intake automation', icon: 'P' },
        ] },
    ],
  },
  { id: 'compare', group: 'Engagement · 1080×1080', name: 'Comparison · vs alternatives', dot: '#5866C2', w: 1080, h: 1080,
    Component: ComparisonPost,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'PrivexBot vs the alternatives' },
      { k: 'competitor', label: 'Competitor column', type: 'text', def: 'Typical AI platform' },
      { k: 'rows', label: 'Rows', type: 'rows', cols: [
        { k: 'label', label: 'Feature' }, { k: 'a', label: 'Them', w: 110 }, { k: 'b', label: 'Us', w: 110 }],
        def: [
          { label: 'Prompts visible to vendor', a: 'Yes', b: 'No' },
          { label: 'Cryptographic attestation', a: 'No', b: 'Hardware TEE' },
          { label: 'Deploy to multiple channels', a: 'API only', b: 'One-click' },
          { label: 'Visual chatflow builder', a: 'No', b: 'Yes' },
          { label: 'Self-hostable models', a: 'Limited', b: 'Yes' },
          { label: 'Time to first deploy', a: '3–7 days', b: '15 minutes' },
        ] },
    ],
  },
  // Carousel slides
  { id: 'car1', group: 'Carousel · 1080×1080', name: 'Carousel · Slide 1 (hook)', dot: '#3947A8', w: 1080, h: 1080,
    Component: CarouselSlide1,
    fields: [
      { k: 'count', label: 'Count badge', type: 'text', def: '1/5' },
      { k: 'hook', label: 'Hook', type: 'textarea', def: 'Five reasons your AI chatbot is leaking data.' },
      { k: 'sub', label: 'Sub-CTA', type: 'text', def: 'Swipe →' },
    ],
  },
  { id: 'car2', group: 'Carousel · 1080×1080', name: 'Carousel · Slide 2 (reason)', dot: '#5866C2', w: 1080, h: 1080,
    Component: CarouselSlide2,
    fields: [
      { k: 'count', label: 'Count badge', type: 'text', def: '2/5' },
      { k: 'num', label: 'Reason number', type: 'text', def: '01' },
      { k: 'reason', label: 'Reason title', type: 'textarea', def: 'Your model vendor logs every prompt for "model improvement".' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'OpenAI, Anthropic, and Google all retain prompts for 30–90 days by default. Even on enterprise plans, opt-out is a request — not a guarantee.' },
    ],
  },
  { id: 'car5', group: 'Carousel · 1080×1080', name: 'Carousel · Slide 5 (close)', dot: '#3947A8', w: 1080, h: 1080,
    Component: CarouselSlide5,
    fields: [
      { k: 'count', label: 'Count badge', type: 'text', def: '5/5' },
      { k: 'title', label: 'Title', type: 'textarea', def: 'The fix is simpler than you think.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Try PrivexBot free' },
    ],
  },
  // === Vertical ===
  { id: 'st-launch', group: 'Vertical · 1080×1920', name: 'Story / Reel · Launch', dot: '#3947A8', w: 1080, h: 1920,
    Component: StoryLaunch,
    fields: [
      { k: 'badge', label: 'Badge', type: 'text', def: 'Now shipping' },
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Launch week · Day 03' },
      { k: 'line1', label: 'Headline line 1', type: 'text', def: 'WhatsApp' },
      { k: 'line2', label: 'Headline line 2', type: 'text', def: 'deploys.' },
      { k: 'sub', label: 'Sub-headline', type: 'text', def: 'Generally available.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Connect your WhatsApp Business number to any agent. Encryption stays end-to-end.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Deploy your first bot' },
    ], },
  { id: 'st-stat', group: 'Vertical · 1080×1920', name: 'Story / Reel · Big stat', dot: '#3E8A5E', w: 1080, h: 1920,
    Component: StoryStat,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'April · build-in-public' },
      { k: 'number', label: 'Number', type: 'text', def: '14' },
      { k: 'unit', label: 'Unit', type: 'text', def: 'min' },
      { k: 'line1', label: 'Caption line 1', type: 'text', def: 'Median time-to-deploy' },
      { k: 'line2', label: 'Caption line 2', type: 'text', def: 'for a new chatbot.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'From blank workspace to live on Discord. Across 1,247 bots created last month.' },
      { k: 'source', label: 'Source', type: 'text', def: 'privexbot.com/changelog' },
    ], },
  { id: 'st-quote', group: 'Vertical · 1080×1920', name: 'Story / Reel · Quote', dot: '#0A0C10', w: 1080, h: 1920,
    Component: StoryQuote,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Customer story · North Loop Health' },
      { k: 'quote', label: 'Quote', type: 'textarea', def: 'PrivexBot was the only platform that let us say yes to AI search without saying yes to leaking customer queries.' },
      { k: 'author', label: 'Author', type: 'text', def: 'Maya Okafor' },
      { k: 'role', label: 'Role', type: 'text', def: 'CTO, North Loop Health' },
    ], },
  { id: 'st-privacy', group: 'Vertical · 1080×1920', name: 'Story / Reel · Privacy', dot: '#5866C2', w: 1080, h: 1920,
    Component: StoryPrivacy,
    fields: [
      { k: 'badge', label: 'Badge', type: 'text', def: 'TEE-attested' },
      { k: 'line1', label: 'Headline line 1', type: 'text', def: 'Your prompts' },
      { k: 'line2', label: 'Headline line 2', type: 'text', def: 'never leave' },
      { k: 'line3', label: 'Headline line 3 (accent)', type: 'text', def: 'the enclave.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Tap to read how PrivexBot encrypts every inference.' },
      { k: 'cta', label: 'CTA', type: 'text', def: 'Learn more' },
    ], },
  // === Thumbnails ===
  { id: 'th-tutorial', group: 'YouTube · 1280×720', name: 'Thumbnail · Tutorial', dot: '#3947A8', w: 1280, h: 720,
    Component: ThumbnailTutorial,
    fields: [
      { k: 'topic', label: 'Topic', type: 'text', def: 'Build a Discord support bot' },
      { k: 'duration', label: 'Duration', type: 'text', def: '14 min' },
      { k: 'difficulty', label: 'Difficulty', type: 'text', def: 'Beginner' },
    ],
  },
  { id: 'th-hottake', group: 'YouTube · 1280×720', name: 'Thumbnail · Hot take', dot: '#0A0C10', w: 1280, h: 720,
    Component: ThumbnailHotTake,
    fields: [
      { k: 'hook', label: 'Hook', type: 'text', def: 'AI vendors are LYING' },
      { k: 'payoff', label: 'Payoff', type: 'text', def: 'about your data.' },
      { k: 'episode', label: 'Episode', type: 'text', def: 'EP 04' },
    ],
  },
  { id: 'th-launch', group: 'YouTube · 1280×720', name: 'Thumbnail · Launch', dot: '#3E8A5E', w: 1280, h: 720,
    Component: ThumbnailLaunch,
    fields: [
      { k: 'feature', label: 'Feature (use \\n)', type: 'textarea', def: 'WhatsApp\ndeploys' },
      { k: 'status', label: 'Status', type: 'text', def: 'NOW LIVE' },
    ],
  },
  // === Covers ===
  { id: 'x-header', group: 'Cover · Banners', name: 'X / Twitter header', dot: '#5866C2', w: 1500, h: 500,
    Component: XHeader,
    fields: [
      { k: 'badge', label: 'Badge', type: 'text', def: 'Inference runs in a Trusted Execution Environment' },
      { k: 'line1', label: 'Headline line 1', type: 'text', def: 'Build chatbots that' },
      { k: 'line2', label: 'Headline line 2 (accent)', type: 'text', def: 'never see your data.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Visual chatflows, RAG knowledge bases, and one-click deploys to Discord, Slack, Telegram, WhatsApp, web.' },
    ], },
  { id: 'li-cover', group: 'Cover · Banners', name: 'LinkedIn cover', dot: '#3947A8', w: 1584, h: 396,
    Component: LinkedInCover,
    fields: [
      { k: 'eyebrow', label: 'Eyebrow', type: 'text', def: 'Privacy-first AI automation' },
      { k: 'line1', label: 'Headline line 1', type: 'text', def: 'Build, deploy,' },
      { k: 'line2', label: 'Headline line 2', type: 'text', def: 'and trust your AI.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'No-code chatflows. Encrypted inference. Cross-platform deployment in a single workspace.' },
      { k: 'wordmark', label: 'Wordmark', type: 'text', def: 'PRIVEXBOT' },
    ], },
  { id: 'twitch', group: 'Cover · Banners', name: 'Twitch banner', dot: '#E5484D', w: 1200, h: 480,
    Component: TwitchBanner,
    fields: [
      { k: 'badge', label: 'Badge', type: 'text', def: 'Live · Building in public' },
      { k: 'title', label: 'Title', type: 'text', def: 'Tuesdays at 14:00 UTC.' },
      { k: 'body', label: 'Body', type: 'textarea', def: 'Live coding sessions, RAG deep dives, and chaotic deploys. Pop in.' },
    ], },
];

export default TEMPLATES;
